version: '3.9'

networks:
  order:

services:
  php:
    build:
      context: .
    container_name: php
    hostname: php
    restart: always
    cap_add:
      - SYS_PTRACE
    working_dir: /var/www/html
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini:ro
      - ./fpm.conf:/usr/local/etc/php-fpm.d/zz-fpm.conf:ro
      - ./ordersprinter-entrypoint:/usr/local/bin/docker-php-entrypoint:ro
      - ordersprinter:/var/www/html
    extra_hosts:
      www.ordersprinter.de: 5.35.225.35
    networks:
      - order

  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - '9999:80'
    volumes:
      - ordersprinter:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./favicon.ico:/favicon.ico:ro
    depends_on:
      php:
        condition: service_started
      database:
        condition: service_started
    networks:
      - order


  database:
    image: mariadb:10.3.34-focal
    container_name: mariadb
    hostname: database
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - mariadb10.3:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASS}
      interval: 10s
      retries: 5
    networks:
      - order

volumes:
  ordersprinter:
  mariadb10.3:
